### ISSUE TITLE
unable to compile the project

### ISSUE THREAD

**Issue by mcheung63** [pentaho/pdi-sdk-plugins#44]
unable to compile the project, pls help
<img width="1341" alt="screen shot 2017-07-31 at 4 39 52 pm" src="https://user-images.githubusercontent.com/1779905/28769628-e72a5b70-760e-11e7-9b5e-851b7b16fbe9.png">

**Comment by tmcsantos** [comment]
Thank you for noticing, you need to copy the contents of this [file](https://github.com/pentaho/maven-parent-poms/blob/master/maven-support-files/settings.xml) to your ~/.m2 directory and save it as settings.xml.
We will update the README with the configurations needed to build the project.

**Comment by mcheung63** [comment]
why don't put those setting into project's pom.xml instead of ~/.m2 ?
