### ISSUE TITLE
build process too slow

### ISSUE THREAD

**Issue by mcheung63** [pentaho/pdi-sdk-plugins#46]
Eveytime i do "mvn package", it download lots of things everytime, wasted a lot of time:

Downloading: http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-registry/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-registry/8.0-SNAPSHOT/maven-metadata.xml (2 KB at 1.3 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/pentaho-kettle/kettle-engine/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/pentaho-kettle/kettle-engine/8.0-SNAPSHOT/maven-metadata.xml (2 KB at 1.6 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/di/pdi/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/di/pdi/8.0-SNAPSHOT/maven-metadata.xml (594 B at 0.8 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/pentaho-kettle/kettle-core/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/pentaho-kettle/kettle-core/8.0-SNAPSHOT/maven-metadata.xml (993 B at 1.1 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/pentaho/metastore/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/pentaho/metastore/8.0-SNAPSHOT/maven-metadata.xml (2 KB at 1.5 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libformula/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libformula/8.0-SNAPSHOT/maven-metadata.xml (2 KB at 0.9 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/reporting-libraries/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/reporting-libraries/8.0-SNAPSHOT/maven-metadata.xml (625 B at 0.7 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/pentaho-reporting/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/pentaho-reporting/8.0-SNAPSHOT/maven-metadata.xml (615 B at 0.6 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libbase/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libbase/8.0-SNAPSHOT/maven-metadata.xml (1000 B at 0.9 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/pdi-engine-api/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/pdi-engine-api/8.0-SNAPSHOT/maven-metadata.xml (989 B at 0.8 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/di/pdi-engine-ext/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/di/pdi-engine-ext/8.0-SNAPSHOT/maven-metadata.xml (603 B at 0.5 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/pentaho/mondrian/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/pentaho/mondrian/8.0-SNAPSHOT/maven-metadata.xml (971 B at 1.1 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-mondrian-parent-pom/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-mondrian-parent-pom/8.0-SNAPSHOT/maven-metadata.xml (609 B at 0.8 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libfonts/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libfonts/8.0-SNAPSHOT/maven-metadata.xml (1001 B at 1.0 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libloader/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libloader/8.0-SNAPSHOT/maven-metadata.xml (1002 B at 1.2 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libpixie/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libpixie/8.0-SNAPSHOT/maven-metadata.xml (1001 B at 1.3 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/engine/classic-core/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/engine/classic-core/8.0-SNAPSHOT/maven-metadata.xml (2 KB at 1.3 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/engine/reporting-engine/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/engine/reporting-engine/8.0-SNAPSHOT/maven-metadata.xml (621 B at 0.8 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libdocbundle/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libdocbundle/8.0-SNAPSHOT/maven-metadata.xml (1005 B at 0.9 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/librepository/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/librepository/8.0-SNAPSHOT/maven-metadata.xml (1006 B at 1.2 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libxml/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libxml/8.0-SNAPSHOT/maven-metadata.xml (999 B at 1.1 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libformat/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libformat/8.0-SNAPSHOT/maven-metadata.xml (1002 B at 1.2 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libserializer/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libserializer/8.0-SNAPSHOT/maven-metadata.xml (1006 B at 1.1 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libswing/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/libswing/8.0-SNAPSHOT/maven-metadata.xml (1001 B at 1.2 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/flute/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/org/pentaho/reporting/library/flute/8.0-SNAPSHOT/maven-metadata.xml (998 B at 1.2 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-database-model/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-database-model/8.0-SNAPSHOT/maven-metadata.xml (2 KB at 1.5 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/pentaho-kettle/kettle-ui-swt/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/pentaho-kettle/kettle-ui-swt/8.0-SNAPSHOT/maven-metadata.xml (991 B at 1.2 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/pentaho-kettle/kettle-dbdialog/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/pentaho-kettle/kettle-dbdialog/8.0-SNAPSHOT/maven-metadata.xml (993 B at 1.1 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-xul-core/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-xul-core/8.0-SNAPSHOT/maven-metadata.xml (2 KB at 1.4 KB/sec)
Downloading: http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-xul-swt/8.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-xul-swt/8.0-SNAPSHOT/maven-metadata.xml (2 KB at 1.2 KB/sec)

**Comment by mcheung63** [comment]
No way to make it faster? I am in hong kong and download from nexus.pentaho.org is just too slow

**Comment by hbfernandes** [comment]
Well, not much we can do here about that. I see 2 options:
- Setup a maven repository closer to you and make it mirror ours, should speed it up a bit.
- Set your snapshot update policy in your settings.xml to "never" and then update once in a while with the -U param when you have more bandwidth or time to wait. Look [here](https://cwiki.apache.org/confluence/display/MAVENOLD/Repository+-+SNAPSHOT+Handling) for more info.
